import Header from "@/components/Header/Header";
import "./globals.css";
import { REM } from "next/font/google";
import { Providers } from "./providers";

const rem = REM({ subsets: ["latin"] });

export const metadata = {
  title: "Yaq App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={rem.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
